---

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
#- name: testrepo
#  type: git
#  source:
#    branch: master
#    uri: git@github.com:rhoughton-pivot/test_pr_resource

- name: pull-requests
  type: pull-request
  source:
    repo: rhoughton-pivot/test_pr_resource

jobs:
- name: test_pr_resource
  public: false
  serial: false
  plan:

  - get: pull-requests
    version: every
    trigger: true
    params:
      fetch_merge: true
  - get: regular-pr
    resource: pull-requests

  - put: pull-requests
    params:
      path: regular-pr
      status: pending

  - task: sleep a while
    config:
      inputs:
      - name: pull-requests
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      outputs:
      - name: some_files
      run:
        path: pull-requests/ci/shellscript.sh
    on_failure:
      put: pull-requests
      params:
        path: regular-pr
        status: failure

  - task:  test-output
    config:
      inputs:
      - name: some_files
      - name: pull-requests
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: cat
        args:
         - "./pull-requests/verfile"
